default: &default
  adapter: mysql2
  pool: 20
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: karadasenmon_development
  username: karadasenmon
  password: karadasenmon
  host: localhost
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: karadasenmon_test
  username: karadasenmon
  password: karadasenmon
  host: localhost

production:
  <<: *default
  database: karadasenmon_production
  username: karadasenmon
  password: ostp0114
  host: localhost
  port: 3306
